name: conda-tui
channels:
  - defaults
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - conda=4.10.3
  - pip:
    - colorama==0.4.4
    - commonmark==0.9.1
    - pygments==2.10.0
    - rich==10.11.0
    - textual==0.1.12
