name: "[CI] conda-tui"

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags: v[0-9]+.[0-9]+.[0-9]+*
  merge_group:

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      # Checkout code and setup miniconda with build dependencies
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        python-version: 3.10
        activate-environment: build-env
        environment-file: etc/build-environment.yml
        auto-activate-base: false
      # Build the package and copy the output into ./conda-bld
    - name: conda build
      shell: bash -l {0}
      run: |
        VERSION=`python -m setuptools_scm` conda build conda.recipe
        mv $CONDA_PREFIX/conda-bld .
    - name: Upload the build artifact
      uses: actions/upload-artifact@v3
      with:
        name: package-${{ github.sha }}
        path: conda-bld
